services:
  - name: web-scraping-app
    type: web
    runtime: docker
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: "0"
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /docs
    autoDeploy: true
